import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

pygame.font.init()
TITLE_FONT = pygame.font.SysFont("Arial", 90)
MENU_FONT = pygame.font.SysFont("Arial", 48)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_VELOCITY = 100
ASTEROID_MAX_VELOCITY = 150

#Player constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 10
PLAYER_SHOOT_COOLDOWN = 1
PLAYER_SHOOT_SPEED = 600
PLAYER_FRICTION = 0.97
PLAYER_RECOIL = 3

SHOT_RADIUS = 5

#Player controls
P1_UP = pygame.K_w
P1_DOWN = pygame.K_s
P1_LEFT = pygame.K_a
P1_RIGHT = pygame.K_d
P1_SHOOT = pygame.K_SPACE

P2_UP = pygame.K_UP
P2_DOWN = pygame.K_DOWN
P2_LEFT = pygame.K_LEFT
P2_RIGHT = pygame.K_RIGHT
P2_SHOOT = pygame.K_RSHIFT